### PR TITLE
chore: unused deprecated user wallet query

### PR DESCRIPTION
**Pull request by nicolasburtey**

### CODE REVIEW

**Comment by Extheoisah** [comment]
> _ No description provided. _

I guess this query is still being used in the mobile repo. we'll need to adjust accordingly.

**Comment by nicolasburtey** [comment]
> > _ No description provided. _
> 
> I guess this query is still being used in the mobile repo. we'll need to adjust accordingly.

@Extheoisah are you sure it's not the accountDefaultWallet used in the mobile wallet?

**Comment by nicolasburtey** [comment]
> > > > _ No description provided. _
> > > 
> > > 
> > > I guess this query is still being used in the mobile repo. we'll need to adjust accordingly.
> > 
> > 
> > @Extheoisah are you sure it's not the accountDefaultWallet used in the mobile wallet?
> 
> Nope. I added that query (`accountDefaultWallet`) about 2weeks ago when developing the POS in galoy pay. I dont think they've changed it in the mobile @daviroo and @UncleSamtoshi can confirm

`userDefaultWalletId` or `accountDefaultWallet` ? 

I have deleted the former. they're duplicated I believe. can you post a link on the function you have added?

**Comment by Extheoisah** [comment]
> > > > > _ No description provided. _
> > > > 
> > > > 
> > > > I guess this query is still being used in the mobile repo. we'll need to adjust accordingly.
> > > 
> > > 
> > > @Extheoisah are you sure it's not the accountDefaultWallet used in the mobile wallet?
> > 
> > 
> > Nope. I added that query (`accountDefaultWallet`) about 2weeks ago when developing the POS in galoy pay. I dont think they've changed it in the mobile @daviroo and @UncleSamtoshi can confirm
> 
> `userDefaultWalletId` or `accountDefaultWallet` ?
> 
> I have deleted the former. they're duplicated I believe. can you post a link on the function you have added?

Here it is https://github.com/GaloyMoney/galoy-client/blob/main/src/graphql/queries/account-default-wallet.ts

**Comment by nicolasburtey** [comment]
> > > > > > _ No description provided. _
> > > > > 
> > > > > 
> > > > > I guess this query is still being used in the mobile repo. we'll need to adjust accordingly.
> > > > 
> > > > 
> > > > @Extheoisah are you sure it's not the accountDefaultWallet used in the mobile wallet?
> > > 
> > > 
> > > Nope. I added that query (`accountDefaultWallet`) about 2weeks ago when developing the POS in galoy pay. I dont think they've changed it in the mobile @daviroo and @UncleSamtoshi can confirm
> > 
> > 
> > `userDefaultWalletId` or `accountDefaultWallet` ?
> > I have deleted the former. they're duplicated I believe. can you post a link on the function you have added?
> 
> Here it is https://github.com/GaloyMoney/galoy-client/blob/main/src/graphql/queries/account-default-wallet.ts



it's not the function I'm deleting? 

I'm deleting `userDefaultWalletId` and you're referring to `accountDefaultWallet`

**Comment by Extheoisah** [comment]
> > > > > > > _ No description provided. _
> > > > > > 
> > > > > > 
> > > > > > I guess this query is still being used in the mobile repo. we'll need to adjust accordingly.
> > > > > 
> > > > > 
> > > > > @Extheoisah are you sure it's not the accountDefaultWallet used in the mobile wallet?
> > > > 
> > > > 
> > > > Nope. I added that query (`accountDefaultWallet`) about 2weeks ago when developing the POS in galoy pay. I dont think they've changed it in the mobile @daviroo and @UncleSamtoshi can confirm
> > > 
> > > 
> > > `userDefaultWalletId` or `accountDefaultWallet` ?
> > > I have deleted the former. they're duplicated I believe. can you post a link on the function you have added?
> > 
> > 
> > Here it is https://github.com/GaloyMoney/galoy-client/blob/main/src/graphql/queries/account-default-wallet.ts
> 
> it's not the function I'm deleting?
> 
> I'm deleting `userDefaultWalletId` and you're referring to `accountDefaultWallet`

Yeah. I'm not against deleting it. I'm just saying I think they use that query (`userDefaultWalletId`) in mobile repo and will need to update the code to use `accountDefaultWallet`

**Pull request closed without merging**
